# Generated by Django 5.2.5 on 2025-11-16 09:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='pfp_kniw7o.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
