# Generated by Django 5.2.5 on 2025-11-16 10:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='pfp_kniw7o', max_length=255, null=True, verbose_name='image'),
        ),
    ]
